# Generated by Django 4.2.1 on 2025-06-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
