# Generated by Django 4.2.1 on 2025-07-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authority',
            field=models.BooleanField(default=False),
        ),
    ]
