# Generated by Django 4.2.1 on 2025-06-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='title',
        ),
    ]
