# Generated by Django 4.2.1 on 2025-09-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('potholes', 'Potholes'), ('street_light', 'Street Light'), ('water_leakage', 'Water Leakage'), ('garbage', 'Garbage'), ('not_labelled', 'Not Labelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('potholes', 'Potholes'), ('street_light', 'Street Light'), ('water_leakage', 'Water Leakage'), ('garbage', 'Garbage'), ('not_labelled', 'Not Labelled')], max_length=50, null=True),
        ),
    ]
