# Generated by Django 4.2.1 on 2025-07-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_latitude_alter_issue_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('potholes', 'Potholes'), ('street_light', 'Street Light'), ('water_leakage', 'Water Leakage'), ('garbage', 'Garbage')], max_length=50),
        ),
    ]
