# Generated by Django 4.2.1 on 2025-09-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_authority_issue_type_alter_issue_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('Potholes', 'Potholes'), ('Street Light', 'Street Light'), ('Water Leakage', 'Water Leakage'), ('Garbage', 'Garbage'), ('Not Labelled', 'Not Labelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('Potholes', 'Potholes'), ('Street Light', 'Street Light'), ('Water Leakage', 'Water Leakage'), ('Garbage', 'Garbage'), ('Not Labelled', 'Not Labelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Verifying', 'Verifying'), ('Accepted', 'Accepted'), ('Assigned to Authority', 'Assigned to Authority')], default='Pending', max_length=50),
        ),
    ]
