# Generated by Django 4.2.1 on 2025-07-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In_progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='open', max_length=50),
        ),
    ]
