# Generated by Django 4.2.1 on 2025-07-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('potholes', 'Potholes'), ('street_light', 'Street Light'), ('water_leakage', 'Water Leakage'), ('garbage', 'Garbage')], max_length=50, null=True),
        ),
    ]
