# Generated by Django 4.2.1 on 2025-09-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_authority_issue_type_alter_issue_issue_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image_after_fix',
            field=models.ImageField(blank=True, null=True, upload_to='issues/fixed/'),
        ),
    ]
