# Generated by Django 4.2.1 on 2025-07-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
