# Generated by Django 4.2.1 on 2025-07-13 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0006_issue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='authority_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('potholes', 'Potholes'), ('traffic_light', 'Traffic Light'), ('street_light', 'Street Light'), ('water_leakage', 'Water Leakage'), ('garbage', 'Garbage')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In_progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Verifying', 'Verifying'), ('Accepted', 'Accepted'), ('Assigned to Authority', 'Assigned to Authority')], default='open', max_length=50),
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(blank=True, choices=[('potholes', 'Potholes'), ('traffic_light', 'Traffic Light'), ('street_light', 'Street Light'), ('water_leakage', 'Water Leakage'), ('garbage', 'Garbage')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
