# Generated by Django 4.2.1 on 2025-07-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issue_issue_type'),
        ('issues', '0006_issue_title'),
    ]

    operations = [
    ]
