# Generated by Django 4.2.1 on 2025-07-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_issue_assigned_to_issue_authority_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('potholes', 'Potholes'), ('street_light', 'Street Light'), ('water_leakage', 'Water Leakage'), ('garbage', 'Garbage')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('potholes', 'Potholes'), ('street_light', 'Street Light'), ('water_leakage', 'Water Leakage'), ('garbage', 'Garbage')], max_length=50, null=True),
        ),
    ]
